config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'


  resources :usuarios
  resources :disciplinas do
    resources :topicos
  end

  get '/login', to: 'sessoes#new'
  post '/login', to: 'sessoes#create'
  get '/logout', to: 'sessoes#destroy'
  delete '/logout', to: 'sessoes#destroy'

  # Rotas adicionadas apenas para definir interação de usuário
  get '/conteudo', to: 'topicos#conteudo'
  get '/tarefas', to: 'topicos#tarefas'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversa.rb
class Conversa < ApplicationRecord
  has_many :mensagens
  has_many :usuarios, through: :participacao_conversa
  has_many :participacao_conversas
  validates :controle_conversa, presence: true
end

app/models/horario.rb
class Horario < ApplicationRecord
  belongs_to :turma
  validates :dia_semana, :hora_inicio, :hora_fim, presence: true
end

app/models/mensagem.rb
class Mensagem < ApplicationRecord
  self.table_name = 'mensagens'
  belongs_to :usuario
  belongs_to :conversa

  validates :descricao, presence: true
end

app/models/participacao.rb
class Participacao < ApplicationRecord
  self.table_name = 'participacoes'
  belongs_to :turma
  belongs_to :usuario

  validates :tipo, presence: true
end

app/models/participacao_conversa.rb
class ParticipacaoConversa < ApplicationRecord
  belongs_to :usuario
  belongs_to :conversa
end

app/models/postagem.rb
class Postagem < ApplicationRecord
  self.table_name = 'postagens'
  belongs_to :usuario
  belongs_to :topico
  validates :descricao, presence: true, length: {maximum: 1000}
end

app/models/topico.rb
class Topico < ApplicationRecord
  belongs_to :usuario
  belongs_to :turma
  has_many :postagems
  validates :titulo, presence: true, length: {maximum: 155}
  validates :descricao, presence: true, length: {maximum: 2000}

  # scope para retornar os topicos dependendo do tipo escolhido
end

app/models/turma.rb
class Turma < ApplicationRecord
  has_many :participacoes, foreign_key: 'turma_id', class_name: 'Participacao'
  has_many :horarios

  validates :codigo_turma, :codigo_disciplina, :disciplina, :ano, :semestre, presence: true

  def alunos
    participantes(:aluno)
  end

  def professores
    participantes(:professor)
  end

  private
    def participantes(tipo)
      Usuario
      .joins(:participacoes)
      .where(participacoes: { tipo: tipo, turma_id: self.id })
    end
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  has_secure_password

  has_many :topicos
  has_many :participacao_conversas
  has_many :postagens, foreign_key: 'usuario_id', class_name: 'Postagem'
  has_many :participacoes, foreign_key: 'usuario_id', class_name: 'Participacao'
  has_many :turmas, through: :participacoes

  validates :iduff, :tipo, :nome, presence: true
  validates :iduff, :cpf, uniqueness: true

end

app/controllers/conversa_controller.rb
class ConversaController < ApplicationController

  def new
    @conversa = Conversa.new
  end

  def create
    @conversa.usuarios = Usuario.find(params[:id])
    @conversa.participacao_conversas = ParticipacaoConversa.find(params[:id])
    if @conversa.save
      redirect_back(fallback_location: root_path)
    else
      flash[:notice] = "Esta conversa não pode ser criada!"
      render 'usuarios/index'
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end

end

app/controllers/horarios_controller.rb
class HorariosController < ApplicationController

  def new
    @horario = Horario.new
  end

  def create
    @horario = Horario.new(horario_params)
    @horario.turma = Turma.find(params[:turma_id])
    if @horario.save
      flash[:success] = "Horario salvo com sucesso!!!"
      redirect_back(fallback_location: root_path) #por enquanto o caminho será o root, mas mudar qnd houver o path correto
    else
      render 'turma/horario' # acredito que seja este o possivel path
    end
  end

  def update
    @horario = Horario.find(params[:id])
    @horario.update(horario_params)
  end

  def destroy
    @horario = Horario.find(params[:id])
    @horario.destroy
  end

  private

  def horario_params
    params.require(:horario).permit(:dia_semana, :hora_inicio, :hora_fim)
  end

end

app/controllers/sessoes_controller.rb
class SessoesController < ApplicationController

  #before_action :block_access, execept: [:destroy]

  def new
  end

  def create

    usuario = Usuario.find_by(cpf: params[:cpf])
    if usuario && usuario.authenticate(params[:senha])
      login usuario
      flash.now[:success] = 'usuário logado'
      redirect_to root_path
    else
      redirect_to login_path
      flash[:warning] = 'cpf ou senha inválida'
    end
  end

  def destroy
    logout
    flash[:success] = 'Você foi deslogado'
    redirect_to root_path
  end

end

app/controllers/topicos.rb
class Topicos < ApplicationController

  def create
    @topico = current_usuario.topicos.build(topico_params)
  end

  def destroy
    @topico.destroy
  end

  private

  def current_usuario
    @topico = current_usuario.topicos.find_by(id: params[:id])
    redirect_to index_path if @topico.nil?
  end

  def topico_params
    @topico = current_usuario.topicos.find_by(id: params(:id))
  end

end

app/controllers/topicos_controller.rb
class TopicosController < ApplicationController

  def new
    @topico = Topico.new
  end

  def create
    @topico.usuario = current_user
    @topico = Topico.new(topico_params)
    if @topico.save
      redirect_back(fallback_location: root_path)
    else
      render 'usuarios/index'
    end
  end

  def destroy
    @topico = Topico.find(params[:id])
    @topico.destroy
  end

  def conteudo
    
  end

  def tarefas

  end

  private

  def topico_params
    params.require(:topico).permit(:titulo, :descricao)
  end

end

app/controllers/turmas_controller.rb
class TurmasControler < ApplicationController

  def create
    @turma = Turma.new(turma_params)
    if @turma.save
      flash[:success] = "Turma criada com sucesso!"
      redirect_back(fallback_location: root_path)
    else
      render 'usuarios/index'
    end
  end

  def index
    @turma = Turma.all
  end

  def edit
  end

  def uptade
    @turma = Turma.find(params[:id])
    @turma.update(turma_params)
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @turma = Turma.find(params[:id])
    @turma.destroy
  end

  def show
    @turma = Turma.find(params[:id])
  end

  private

  def turma_params
    params.require(:user).permit(:codigo_turma, :codigo_disciplina, :discilpina, :ano, :semestre )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessoes_helper.rb
module SessoesHelper

  def login (usuario)
    session[:usuario_id] = usuario.id
  end

  def usuario_atual
    @usuario_atual ||= Usuario.find_by(id: session[:usuario_id])
  end

  def block_access
    if usuario_atual.present?
      redirect_to root_path
    end
  end

  def logado?
    !usuario_atual.nil?
  end

  def logout
    session.delete(:usuario_id)
    @usuario_atual = nil
  end


end

app/helpers/turmas_helper.rb
module TurmasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
<head>
  <title>Sistema UFF</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- instala fontawesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.1/css/all.css" integrity="sha384-O8whS3fhG2OnA5Kas0Y9l3cfpmYjapjI0E4theH4iuMD+pLhbf6JI0jIMfYcK3yZ" crossorigin="anonymous">

</head>
<body>
<%= render 'partials/header' %>
  <!-- Componente de alerta que avisa os usuários sobre ações feitas -->
  <!-- TODO: Alterar componente para flutuante e absolutamente posicionado -->
<% flash.each do |nome, msg| %>
    <div class="alert alert-<%= nome %> alert-dismissible fade show fixed-top mx-auto col-sm-8 mt-1" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <%= msg %>
      </div>
  <% end %>
  <div class="h-100">
    <div class="row no-gutters h-100">
      <div class="col-md-2 bg-dark d-none d-lg-block">
        <%= render 'partials/sidebar' %>
      </div>
      <main class="col h-100" style="overflow: hidden">
        <%= yield %>
      </main>
    </div>
  </div>
</body>
</html>

app/views/partials/_footer.html.erb
<footer class="footer">
      <div class="container">
        <span class="text-muted">Place sticky footer content here.</span>
      </div>
</footer>

app/views/partials/_header.html.erb
<header>
  <nav class="navbar navbar-dark bg-dark navbar-expand-lg">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <%= link_to 'ConexãoUFF', root_path, class: 'navbar-brand' %>

    <div class="form-inline my-2 my-lg-0">
      <% if logado? %>
        <span class="navbar-text mr-sm-4"> Bem-vindo, <%= usuario_atual.nome %></span>
        <%= link_to 'Sair', logout_path, method: 'delete', class: 'nav-link btn btn-outline-info btn-md' %>
      <% else %>
        <%= link_to 'Entrar', login_path, class: 'nav-link btn btn-outline-info btn-md' %>
      <% end %>
    </div>
  </nav>
</header>

app/views/partials/_sidebar.html.erb
<nav class="nav nav-pills flex-column list-group list-group-flush">

  <%= link_to root_path, class: 'nav-item list-group-item list-group-item-action list-group-item-dark' do %>
    <i class="fas fa-home"></i>
    <span class="pl-2">Página Inicial</span>
  <% end %>

  <%= link_to '#', class: 'nav-item list-group-item list-group-item-action list-group-item-dark' do %>
    <i class="fas fa-map"></i>
    <span class="pl-2">Plano de Estudo</span>
  <% end %>

  <%= link_to disciplinas_path, class: 'nav-item list-group-item list-group-item-action list-group-item-dark' do %>
    <i class="fas fa-book"></i>
    <span class="pl-2">Disciplinas</span>
  <% end %>

  <%= link_to '#', class: 'nav-item list-group-item list-group-item-action list-group-item-dark' do %>
    <i class="fas fa-calendar"></i>
    <span class="pl-2">Calendário</span>
  <% end %>

  <%= link_to '#', class: 'nav-item list-group-item list-group-item-action list-group-item-dark' do %>
    <i class="fas fa-comment"></i>
    <span class="pl-2">Mensagens</span>
  <% end %>

</ul>

app/views/partials/_sidebar_topicos.html.erb
<nav class="nav flex-column">
  <div class="nav-item text-center p-3">
    <img src="https://placekitten.com/g/200/200" alt="profile" class="img-thumbnail rounded img-fluid">
  </div>
  <div class="nav-item list-group list-group-flush">
    <%= link_to conteudo_path, class: 'nav-item list-group-item list-group-item-action' do %>
      <i class="fas fa-book-open"></i>
      Conteúdo
    <% end %>
    <%= link_to tarefas_path, class: 'nav-item list-group-item list-group-item-action' do %>
      <i class="fas fa-tasks"></i>
      Tarefas
    <% end %>
    <%= link_to '#', class: 'nav-item list-group-item list-group-item-action' do %>
      <i class="fas fa-user-friends"></i>
      Colegas de Turma
    <% end %>
  </div>
</nav>

app/views/partials/_topico.html.erb
<div class="topico bg-secondary text-light card mb-5">
  <div class="card-header">
    <div class="details float-right">
      <span class="author">Augusto José</span> -
      <span class="date"><%= Date.new(2018, 10, 04) %></span>
    </div>
    <h4>Titulo</h4>
  </div>
  <div class="card-body">
    <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>
  <div class="card-footer">
    <p class="float-right">prazo: 08-02-2017</p>
  </div>
  <div class="comentarios list-group list-group-flush text-dark">
    <div class="list-group-item font-weight-bold text-center">Comentários</div>
    <div class="comentario list-group-item">
      <div class="relato">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </div>
      <div class="detalhes float-right">
        <span class="author">Aluno 1</span> -
        <span class="date"><%= Date.new(2018, 7, 17) %></span>
      </div>
    </div>
    <div class="comentario list-group-item">
      <div class="relato">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </div>
      <div class="detalhes float-right">
        <span class="author">Aluno 1</span> -
        <span class="date"><%= Date.new(2018, 7, 17) %></span>
      </div>
    </div>

    <form class="list-group-item insere-comentario">
      <div class="form-group">
        <input type="text" name="relato" id="relato" class="form-control" placeholder="entre com seu comentário">
      </div>
      <button type="submit" class="btn btn-dark btn-block">Enviar</button>
    </form>
  </div>
</div>